# Generated by Django 6.0.2 on 2026-02-20 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('setor', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('foto_url', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=200)),
                ('perfil', models.CharField(choices=[('master', 'Admin Master'), ('usuario', 'Usuario'), ('operador', 'Operador')], default='usuario', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('senha_atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('notebook', 'Notebook'), ('celular', 'Celular'), ('tablet', 'Tablet'), ('outro', 'Outro')], default='notebook', max_length=50)),
                ('tipo_descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('patrimonio', models.CharField(blank=True, max_length=50, null=True)),
                ('serial', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(choices=[('taboca', 'Taboca'), ('terceira', 'Terceira'), ('pessoal', 'Pessoal')], default='taboca', max_length=20)),
                ('terceira_nome', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponivel'), ('em_uso', 'Em uso'), ('manutencao', 'Manutencao')], default='em_uso', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empregado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='dispositivos.empregado')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Baixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('devolucao', 'Devolucao'), ('demissao', 'Demissao'), ('troca', 'Troca'), ('transferencia', 'Transferencia'), ('furto_perda', 'Furto/Perda')], max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('usuario_nome', models.CharField(blank=True, max_length=200, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baixas', to='dispositivos.dispositivo')),
                ('empregado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispositivos.empregado')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CHECK-IN', 'Check-in'), ('CHECK-OUT', 'Check-out')], max_length=10)),
                ('operador_nome', models.CharField(blank=True, max_length=200, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='dispositivos.dispositivo')),
                ('empregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='dispositivos.empregado')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
