# Generated by Django 6.0.2 on 2026-03-30 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponivel'), ('em_uso', 'Em uso'), ('danificado', 'Danificado')], default='disponivel', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qrcode', to='dispositivos.dispositivo')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
    ]
