# Generated by Django 6.0.2 on 2026-04-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='empregado',
            name='documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empregado',
            name='empresa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='empregado',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empregado',
            name='tipo_pessoa',
            field=models.CharField(choices=[('proprio', 'Proprio'), ('terceiro', 'Terceiro'), ('visitante', 'Visitante')], default='proprio', max_length=20),
        ),
        migrations.AlterField(
            model_name='empregado',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empregado',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empregado',
            name='setor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponivel'), ('em_uso', 'Em uso'), ('danificado', 'Danificado'), ('inutilizado', 'Inutilizado')], default='disponivel', max_length=20),
        ),
    ]
