# Generated by Django 6.0.2 on 2026-04-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_empregado_documento_empregado_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dias_validade_senha',
            field=models.IntegerField(default=90, help_text='Quantos dias a senha e valida (padrao corporativo: 90)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='precisa_trocar_senha',
            field=models.BooleanField(default=True, help_text='True no primeiro login ou quando admin resetou a senha'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha_expira_em',
            field=models.DateTimeField(blank=True, help_text='Data em que a senha expira e o usuario sera forcado a trocar', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tentativas_login_falhas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=255),
        ),
    ]
