# Generated by Django 6.0.2 on 2026-05-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0005_usuario_username_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='temp', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
