# Generated by Django 6.0.2 on 2026-05-12 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0006_alter_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nome', models.CharField(blank=True, max_length=200)),
                ('usuario_username', models.CharField(blank=True, max_length=100)),
                ('acao', models.CharField(choices=[('LOGIN', 'Login realizado'), ('LOGOUT', 'Logout realizado'), ('LOGIN_FALHA', 'Tentativa de login falhada'), ('SENHA_TROCADA', 'Senha alterada pelo proprio usuario'), ('SENHA_RESETADA', 'Senha resetada por administrador'), ('SENHA_EXPIRADA', 'Senha expirou'), ('USUARIO_CRIADO', 'Novo usuario criado'), ('USUARIO_EDITADO', 'Usuario editado'), ('USUARIO_DESATIVADO', 'Usuario desativado'), ('DISPOSITIVO_CRIADO', 'Novo dispositivo cadastrado'), ('DISPOSITIVO_EDITADO', 'Dispositivo editado'), ('DISPOSITIVO_BAIXA', 'Dispositivo dado baixa'), ('QR_GERADO', 'QR Code gerado em lote'), ('QR_VINCULADO', 'QR Code vinculado a dispositivo'), ('QR_DESVINCULADO', 'QR Code desvinculado'), ('QR_INUTILIZADO', 'QR Code inutilizado'), ('SCAN_CHECKIN', 'Check-in via scan'), ('SCAN_CHECKOUT', 'Check-out via scan'), ('OUTRO', 'Outra acao')], max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('objeto_tipo', models.CharField(blank=True, max_length=50)),
                ('objeto_id', models.IntegerField(blank=True, null=True)),
                ('objeto_descricao', models.CharField(blank=True, max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('sucesso', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to='dispositivos.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='dispositivo_timesta_546d99_idx'), models.Index(fields=['usuario', '-timestamp'], name='dispositivo_usuario_8ac673_idx'), models.Index(fields=['acao', '-timestamp'], name='dispositivo_acao_bc9fca_idx')],
            },
        ),
    ]
